# Generated by Django 3.2.7 on 2022-03-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Sex',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_list',
            field=models.TextField(blank=True, default='[-1, -2]'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', help_text='Введите свой пол', max_length=1),
        ),
    ]
