# Generated by Django 3.2.7 on 2022-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20220325_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=20.224, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=6.382, max_digits=6),
        ),
    ]
